// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCySGpS5jyHJ4uKxD2O5m0HunTniUDN-W0',
    appId: '1:724985400259:web:84ef75017f3bcb1d908b76',
    messagingSenderId: '724985400259',
    projectId: 'flutter-full-stack-news-app',
    authDomain: 'flutter-full-stack-news-app.firebaseapp.com',
    storageBucket: 'flutter-full-stack-news-app.appspot.com',
    measurementId: 'G-QT77QKL3D5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDNGxrA58DSj7zJ6hzCskSf2gX35x5-IXY',
    appId: '1:724985400259:android:af30851ff1a045a8908b76',
    messagingSenderId: '724985400259',
    projectId: 'flutter-full-stack-news-app',
    storageBucket: 'flutter-full-stack-news-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBwjD86a8A9El-1wtUd5n3fwAeIQ8NTIPY',
    appId: '1:724985400259:ios:0978768bd543ddea908b76',
    messagingSenderId: '724985400259',
    projectId: 'flutter-full-stack-news-app',
    storageBucket: 'flutter-full-stack-news-app.appspot.com',
    iosBundleId: 'com.example.fullstackFirebaseNewsApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBwjD86a8A9El-1wtUd5n3fwAeIQ8NTIPY',
    appId: '1:724985400259:ios:4f5adb7c77aa0c4c908b76',
    messagingSenderId: '724985400259',
    projectId: 'flutter-full-stack-news-app',
    storageBucket: 'flutter-full-stack-news-app.appspot.com',
    iosBundleId: 'com.example.fullstackFirebaseNewsApp.RunnerTests',
  );
}
